---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  SAM template for shiftboard-bot

Parameters:
  AppName:
    Type: String
    Default: shiftboard-bot
  Env:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
  TableName:
    Type: String
    Default: shiftboard-bot
  SSMAPIParameterPath:
    Type: String
    Default: "shiftboard/api"
  SSMNotificationsParameterPath:
    Type: String
    Default: "shiftboard/notification"

Globals:
  Function:
    Timeout: 10
    Runtime: go1.x
    MemorySize: 128
    Tags:
      app:
        Ref: AppName
      env:
        Ref: Env

Resources:
  DatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      Tags:
        - Key: app
          Value:
            Ref: AppName
        - Key: env
          Value:
            Ref: Env
      TableName:
        Ref: TableName
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  RetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/retriever
      Environment:
        Variables:
          WORKER_FUNCTION:
            Ref: WorkerFunction
          NOTIFICATION_FUNCTION:
            Ref: NotificationFunction
      Handler: retriever
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: NotificationFunction
        - LambdaInvokePolicy:
            FunctionName:
              Ref: WorkerFunction
        - SSMParameterReadPolicy:
            ParameterName:
              Ref: SSMAPIParameterPath

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/worker
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
          NOTIFICATION_FUNCTION:
            Ref: NotificationFunction
      Handler: worker
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DatabaseTable
        - LambdaInvokePolicy:
            FunctionName:
              Ref: NotificationFunction

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/notification
      Handler: notification
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - SESCrudPolicy:
            IdentityName: "*"
        - SSMParameterReadPolicy:
            ParameterName:
              Ref: SSMNotificationsParameterPath

  RetrieverFunctionSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(15 minutes)"
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - RetrieverFunction
              - Arn
          Id: RetrieverFunctionV1

  RetrieverInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: RetrieverFunction
      Action: "lambda:InvokeFunction"
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - RetrieverFunctionSchedule
          - Arn

Outputs:
  RetrieverFunctionName:
    Description: Retriever function name
    Value:
      Ref: RetrieverFunction

  WorkerFunctionName:
    Description: Worker function name
    Value:
      Ref: WorkerFunction

  NotificationFunctionName:
    Description: Notification function name
    Value:
      Ref: NotificationFunction
