---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for shiftboard-bot

Parameters:
  TableNameParameter:
    Type: String
    Default: ShiftBoard
  # EmailIdentityParameter:
  #   Type: String
  DomainIdentityParameter:
    Type: String

Resources:
  DatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref TableNameParameter
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  RetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/retriever
      Environment:
        Variables:
          PROCESSOR_FUNCTION: !Ref ProcessorFunction
          NOTIFICATION_FUNCTION: !Ref NotificationFunction
      Handler: retriever
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotificationFunction

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processor
      Environment:
        Variables:
          TABLE_NAME: !Ref TableNameParameter
          NOTIFICATION_FUNCTION: !Ref NotificationFunction
      Handler: processor
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DatabaseTable
        - LambdaInvokePolicy:
            FunctionName: !Ref NotificationFunction

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/notification
      Handler: notification
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref DomainIdentityParameter

#   SenderEmailIdentity:
#     Type: AWS::SES::EmailIdentity
#     Properties:
#       EmailIdentity: !Ref EmailIdentityParameter
#

Outputs:
  RetrieverFunctionName:
    Description: Retriever function name
    Value: !Ref RetrieverFunction

  ProcessorFunctionName:
    Description: Processor function name
    Value: !Ref ProcessorFunction

  NotificationFunctionName:
    Description: Notification function name
    Value: !Ref NotificationFunction
