---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for shiftboard-bot

Parameters:
  TableNameParameter:
    Type: String
  DomainIdentityParameter:
    Type: String
  SSMAPIParameter:
    Type: String
  SSMNotificationsParameter:
    Type: String

Resources:
  DatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Ref: TableNameParameter
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  RetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/retriever
      Environment:
        Variables:
          WORKER_FUNCTION:
            Ref: WorkerFunction
          NOTIFICATION_FUNCTION:
            Ref: NotificationFunction
      Handler: retriever
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: WorkerFunction
        - LambdaInvokePolicy:
            FunctionName:
              Ref: NotificationFunction

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/worker
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableNameParameter
          NOTIFICATION_FUNCTION:
            Ref: NotificationFunction
      Handler: worker
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DatabaseTable
        - LambdaInvokePolicy:
            FunctionName:
              Ref: NotificationFunction

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/notification
      Handler: notification
      MemorySize: 128
      Timeout: 10
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - SESCrudPolicy:
            IdentityName:
              Ref: DomainIdentityParameter

  RetrieverFunctionSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - RetrieverFunction
              - Arn
          Id: RetrieverFunctionV1
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: NotificationFunction

  # PermissionForEventsToInvokeLambda:
  #  Type: AWS::Lambda::Permission
  #  Properties:
  #    FunctionName:
  #      Ref: RetrieverFunction
  #    Action: "lambda:InvokeFunction"
  #    Principal: events.amazonaws.com
  #    SourceArn:
  #      Fn::GetAtt:
  #        - RetrieverFunctionSchedule
  #        - Arn

Outputs:
  RetrieverFunctionName:
    Description: Retriever function name
    Value: 
      Ref: RetrieverFunction

  WorkerFunctionName:
    Description: Worker function name
    Value:
      Ref: WorkerFunction

  NotificationFunctionName:
    Description: Notification function name
    Value:
      Ref: NotificationFunction
