name: ci-workflow

on: [push]

env:
  GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
  GOPRIVATE: github.com/edevenport/shiftboard-sdk-go

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Update GitHub config
        run: git config --global url.https://$GH_ACTIONS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test retriever
        run: go test -v *.go
        working-directory: ./functions/retriever

      - name: Test worker
        run: go test -v *.go
        working-directory: ./functions/worker

      - name: Test notification
        run: go test -v *.go
        working-directory: ./functions/notification

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Update GitHub config
        run: git config --global url.https://$GH_ACTIONS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint AWS SAM template 
        run: yamllint template.yaml

      - name: Lint retriever
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          working-directory: ./functions/retriever

      - name: Lint worker
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          working-directory: ./functions/worker

      - name: Lint notification
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          working-directory: ./functions/retriever
